# Generated by Django 4.1.3 on 2022-12-04 01:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=15, verbose_name='Name')),
                ('body', models.CharField(db_index=True, max_length=150, verbose_name='Body')),
                ('DateTime', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Likes')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
