# Generated by Django 4.1.3 on 2022-12-02 16:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='social',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Likes'),
        ),
    ]
